const DOMAINS = [
  { id: 'nature', name: 'Nature literacy', short: 'Nature', color: '#4de4ff', description: 'Genes, species, ecological roles and sensitivity' },
  { id: 'ecosystems', name: 'Ecosystems & dependencies', short: 'Ecosystems', color: '#62f2bd', description: 'Functions, services, connectivity and resilience' },
  { id: 'mitigation', name: 'Mitigation & restoration', short: 'Mitigation', color: '#ffca67', description: 'Avoidance, minimisation, restoration and adaptive action' },
  { id: 'evidence', name: 'Measurement & evidence', short: 'Evidence', color: '#ba9cff', description: 'Indicators, baselines, claims and decision quality' },
  { id: 'airbus', name: 'Airbus applied decisions', short: 'Airbus', color: '#ff7f91', description: 'A400M, Eurofighter, sites, procurement and operations' },
];

const QUESTIONS = [
  {
    id: 1, domain: 'nature', difficulty: 'Foundation',
    question: 'Which three levels are normally considered when describing the diversity of nature?',
    options: ['Climate, water and soil', 'Genes, species and ecosystems', 'Plants, animals and fungi only', 'Local, regional and global'], correct: 1,
    explanation: 'Nature is diverse within species through genetic variation, between different species, and across ecosystems. These levels interact: reduced genetic variation can weaken a species, while habitat degradation can affect many species at once.',
    takeaway: 'Avoid reducing nature to a simple species count; the condition and diversity of all three levels matter.',
  },
  {
    id: 2, domain: 'nature', difficulty: 'Foundation',
    question: 'What makes an endemic species particularly important in a local assessment?',
    options: ['It only lives at night', 'Its natural distribution is restricted to a limited area', 'It has been introduced by people', 'It is abundant everywhere'], correct: 1,
    explanation: 'An endemic species occurs naturally within a restricted geographic area. A local impact can therefore affect a large share of its total population or habitat, which may increase the significance of the decision.',
    takeaway: 'Distribution and irreplaceability are as important as the number of individuals observed on site.',
  },
  {
    id: 3, domain: 'nature', difficulty: 'Foundation',
    question: 'Why can genetic diversity make a population more resilient?',
    options: ['It removes all competition', 'Some individuals may be better able to tolerate change', 'It prevents every disease', 'It makes all populations identical'], correct: 1,
    explanation: 'Genetic variation creates a wider range of traits within a population. When disease, temperature or habitat conditions change, that variation increases the chance that some individuals survive and reproduce.',
    takeaway: 'A population can appear numerous while still being vulnerable if its genetic diversity is very low.',
  },
  {
    id: 4, domain: 'nature', difficulty: 'Applied',
    question: 'What is the key difference between a non-native species and an invasive species?',
    options: ['There is no difference', 'An invasive species causes harm as it establishes and spreads', 'A non-native species is always poisonous', 'An invasive species only occurs in cities'], correct: 1,
    explanation: 'A non-native species has been moved beyond its natural range, but it is not automatically invasive. It becomes invasive when establishment and spread create ecological, economic or social harm.',
    takeaway: 'Management should be based on evidence of risk and impact, not simply on whether a species is unfamiliar.',
  },
  {
    id: 5, domain: 'nature', difficulty: 'Applied',
    question: 'Why can the loss of a keystone species create disproportionate consequences?',
    options: ['Every species is interchangeable', 'It can trigger cascading changes through a food web', 'It changes only the appearance of a landscape', 'It always increases ecosystem stability'], correct: 1,
    explanation: 'A keystone species has an ecological influence that is large relative to its abundance. Its removal can change prey, predators, vegetation or habitat structure and produce effects across the wider system.',
    takeaway: 'Ecological importance cannot be inferred from abundance alone.',
  },
  {
    id: 6, domain: 'nature', difficulty: 'Applied',
    question: 'What is a bioindicator?',
    options: ['A mandatory financial record', 'An organism or community that provides evidence about environmental condition', 'Any species shown in a campaign', 'A sensor that measures only temperature'], correct: 1,
    explanation: 'Bioindicators respond to environmental conditions in ways that can reveal pollution, habitat quality or ecological change. Their interpretation requires an appropriate method, reference condition and understanding of other influencing factors.',
    takeaway: 'A bioindicator is useful only when its ecological response and measurement method are understood.',
  },
  {
    id: 7, domain: 'nature', difficulty: 'Foundation',
    question: 'Which ecological function is performed by many insects, birds and bats?',
    options: ['Sealing soil', 'Pollinating plants', 'Increasing artificial light', 'Eliminating food webs'], correct: 1,
    explanation: 'Many flowering plants depend on animals to move pollen and enable reproduction. Pollination supports wild vegetation, crops and the food webs and habitats associated with those plants.',
    takeaway: 'Protecting pollinators also means protecting nesting sites, food sources and seasonal continuity.',
  },
  {
    id: 8, domain: 'nature', difficulty: 'Applied',
    question: 'Why can artificial light at night affect wildlife even when no animals are visibly injured?',
    options: ['It improves every habitat', 'It can alter orientation, activity and biological cycles', 'It always reduces noise', 'It increases genetic diversity'], correct: 1,
    explanation: 'Light can change movement, feeding, migration, reproduction and predator–prey interactions. Effects may occur beyond the illuminated surface because sky glow and reflected light extend the exposure area.',
    takeaway: 'First question whether light is needed; then control duration, intensity, direction and spectrum.',
  },
  {
    id: 9, domain: 'nature', difficulty: 'Advanced',
    question: 'Why is a food-web perspective stronger than assessing each species in isolation?',
    options: ['It assumes all species respond identically', 'It considers ecological relationships and indirect effects', 'It removes the need for field data', 'It focuses only on predators'], correct: 1,
    explanation: 'Species are connected by feeding, competition, pollination, decomposition and habitat relationships. A pressure on one group can therefore affect other groups even when they are not directly exposed.',
    takeaway: 'Assessment should consider functions and interactions, not only a checklist of species present.',
  },
  {
    id: 10, domain: 'nature', difficulty: 'Applied',
    question: 'Before work begins during a sensitive breeding period, which action provides the best basis for prevention?',
    options: ['Start work and observe later', 'Carry out a competent ecological survey first', 'Increase the lighting', 'Remove vegetation immediately'], correct: 1,
    explanation: 'A proportionate pre-work survey can identify nests, shelters, movement routes or sensitive receptors. The findings allow the design, sequence, timing and exclusion zones to be adapted before disturbance occurs.',
    takeaway: 'Early ecological information creates more options for avoidance and reduces emergency changes later.',
  },

  {
    id: 11, domain: 'ecosystems', difficulty: 'Foundation',
    question: 'What are ecosystem services?',
    options: ['Commercial gardening services', 'Contributions that ecosystems make to people and economic activity', 'Agricultural products only', 'Benefits supplied only by protected areas'], correct: 1,
    explanation: 'Ecosystems contribute through material provision, regulation of processes and non-material values. These contributions depend on underlying ecological functions such as nutrient cycling, soil formation and habitat provision.',
    takeaway: 'An organisation can depend on nature even when the dependency is indirect or located in its value chain.',
  },
  {
    id: 12, domain: 'ecosystems', difficulty: 'Foundation',
    question: 'Which service can a healthy wetland provide?',
    options: ['Increasing erosion', 'Storing water, filtering pollutants and providing habitat', 'Preventing every drought', 'Removing all seasonal variation'], correct: 1,
    explanation: 'Wetlands can slow water, retain sediment and nutrients, support species and influence local hydrology. Their performance depends on condition, scale, connectivity and the intensity of the pressure they face.',
    takeaway: 'A wetland reduces certain risks; it should not be presented as eliminating all flood or water-quality risk.',
  },
  {
    id: 13, domain: 'ecosystems', difficulty: 'Foundation',
    question: 'What does ecological connectivity describe?',
    options: ['Digital coverage in rural areas', 'The ability of organisms and ecological processes to move between habitats', 'A road linking two buildings', 'Keeping wildlife inside one enclosure'], correct: 1,
    explanation: 'Connectivity enables dispersal, migration, gene flow and access to resources. It depends on the quality and arrangement of habitat, barriers, stepping stones and the movement needs of the species concerned.',
    takeaway: 'A corridor drawn on a map is not automatically functional; its use and condition must be assessed.',
  },
  {
    id: 14, domain: 'ecosystems', difficulty: 'Foundation',
    question: 'Why should soil be treated as a living system rather than an inert surface?',
    options: ['It contains no organisms', 'It regulates water, nutrients, carbon and supports biological communities', 'It is relevant only for agriculture', 'It always recovers immediately after sealing'], correct: 1,
    explanation: 'Soil contains complex biological communities and provides infiltration, nutrient cycling, carbon storage and physical support. Compaction, contamination, erosion and sealing can reduce these functions for long periods.',
    takeaway: 'Protect soil condition and function, not just the visible surface area.',
  },
  {
    id: 15, domain: 'ecosystems', difficulty: 'Applied',
    question: 'What is a common consequence of habitat fragmentation?',
    options: ['Improved movement for every species', 'Population isolation and stronger edge effects', 'Automatic creation of new habitat', 'No change outside the project boundary'], correct: 1,
    explanation: 'Fragmentation divides continuous habitat into smaller patches. It can obstruct movement, reduce gene flow and expose a greater proportion of habitat to light, noise, predators or invasive species at the edges.',
    takeaway: 'The shape, connection and surrounding land use of habitat can matter as much as its total area.',
  },
  {
    id: 16, domain: 'ecosystems', difficulty: 'Applied',
    question: 'What is the purpose of an ecological baseline?',
    options: ['To justify a decision already taken', 'To define the starting condition against which change can be assessed', 'To replace future monitoring', 'To record expenditure only'], correct: 1,
    explanation: 'A baseline describes relevant receptors and conditions before an intervention, using stated methods, boundaries and timing. It allows later observations to be compared and helps distinguish project effects from natural variation.',
    takeaway: 'Without a credible baseline, claims of improvement or deterioration are difficult to verify.',
  },
  {
    id: 17, domain: 'ecosystems', difficulty: 'Advanced',
    question: 'Why should an industrial site be assessed at landscape or catchment scale?',
    options: ['The site is ecologically isolated', 'Water, species and pressures cross administrative boundaries', 'Only national data are valid', 'Local stakeholders are irrelevant'], correct: 1,
    explanation: 'Species move beyond fences, drainage connects locations and suppliers or neighbouring land uses can affect the same receptors. A wider scale reveals cumulative effects, dependencies and opportunities that a site-only view misses.',
    takeaway: 'Set boundaries according to ecological processes, not only property ownership.',
  },
  {
    id: 18, domain: 'ecosystems', difficulty: 'Applied',
    question: 'What is a nature dependency?',
    options: ['A change caused by an activity', 'An ecosystem contribution that an activity relies upon', 'Any environmental legal requirement', 'A communications objective'], correct: 1,
    explanation: 'Dependencies include reliable water, stable ground, climate regulation, materials and protection from hazards. A dependency can create operational or supply-chain risk when the supporting ecosystem deteriorates.',
    takeaway: 'Impacts describe what the organisation changes; dependencies describe what the organisation needs.',
  },
  {
    id: 19, domain: 'ecosystems', difficulty: 'Applied',
    question: 'What distinguishes a credible nature-based solution?',
    options: ['It uses natural imagery', 'It addresses a real challenge while delivering verifiable ecological benefits', 'It always consists of tree planting', 'It replaces every engineered solution'], correct: 1,
    explanation: 'A credible solution is designed for the local ecological and social context, addresses a defined challenge and avoids harm or displacement. It includes measurable outcomes, governance and long-term management.',
    takeaway: 'Judge the function, context and evidence—not whether the intervention simply looks natural.',
  },
  {
    id: 20, domain: 'ecosystems', difficulty: 'Advanced',
    question: 'What is the difference between ecosystem resistance and recovery?',
    options: ['There is no difference', 'Resistance limits change during disturbance; recovery concerns the return afterwards', 'Recovery occurs before disturbance', 'Resistance means an ecosystem never changes'], correct: 1,
    explanation: 'Resistance is the capacity to withstand a pressure without major change. Recovery is the capacity to regain structure or function afterwards; resilience can involve both, but no ecosystem is immune to unlimited disturbance.',
    takeaway: 'Monitoring should examine both the immediate response and the trajectory after the pressure ends.',
  },

  {
    id: 21, domain: 'mitigation', difficulty: 'Foundation',
    question: 'What is the correct order of the mitigation hierarchy?',
    options: ['Offset, restore, minimise, avoid', 'Avoid, minimise, restore and only then offset residual impacts', 'Restore, avoid, offset, minimise', 'Measure, communicate, offset, close'], correct: 1,
    explanation: 'Avoidance prevents an impact from occurring. Remaining impacts are minimised, affected areas are restored, and compensation is considered only for residual impacts that remain after the earlier steps.',
    takeaway: 'Do not use a future restoration or offset to bypass a feasible avoidance option.',
  },
  {
    id: 22, domain: 'mitigation', difficulty: 'Applied',
    question: 'Which action best applies the avoidance step of the hierarchy?',
    options: ['Relocating work away from a sensitive habitat', 'Planting vegetation after construction', 'Publishing a campaign', 'Measuring damage at the end'], correct: 0,
    explanation: 'Changing the location, layout, technology or schedule before the impact occurs can remove the interaction altogether. Avoidance usually provides greater certainty than attempting to repair ecological damage later.',
    takeaway: 'Early design decisions create the strongest opportunities to avoid impacts.',
  },
  {
    id: 23, domain: 'mitigation', difficulty: 'Applied',
    question: 'If essential security lighting may disturb nocturnal fauna, which response best reflects minimisation?',
    options: ['Remove every light regardless of safety', 'Limit duration, intensity, direction and spill while meeting the safety need', 'Add more lighting without assessment', 'Assume the effect is insignificant'], correct: 1,
    explanation: 'Where the activity cannot be avoided, minimisation reduces the magnitude, duration or extent of exposure. Lighting design should respond to the safety function and the sensitivity of the receptors identified.',
    takeaway: 'A good measure addresses the impact pathway while preserving the legitimate operational requirement.',
  },
  {
    id: 24, domain: 'mitigation', difficulty: 'Applied',
    question: 'What does a robust ecological restoration plan need?',
    options: ['A species list only', 'A reference condition, objectives, actions, indicators, thresholds and maintenance', 'A photograph from the first day', 'A promise without a timeframe'], correct: 1,
    explanation: 'Restoration aims to place an ecosystem on a credible recovery trajectory. It needs a reference, measurable outcomes, an implementation method, resources, monitoring and responses if progress is insufficient.',
    takeaway: 'Restoration is a managed process over time, not a one-day planting activity.',
  },
  {
    id: 25, domain: 'mitigation', difficulty: 'Advanced',
    question: 'Why is ecological compensation not equivalent to avoidance?',
    options: ['Compensation always works immediately', 'Some values are irreplaceable and compensation carries uncertainty and time lags', 'Avoidance is only a communications action', 'Compensation needs no monitoring'], correct: 1,
    explanation: 'A recreated habitat may differ in condition, location, function and maturity from what is lost. Some impacts cannot be compensated with confidence, especially where receptors are critical, unique or slow to recover.',
    takeaway: 'Compensation is the final step for residual impact, not permission to ignore ecological limits.',
  },
  {
    id: 26, domain: 'mitigation', difficulty: 'Advanced',
    question: 'What does additionality mean in a restoration or compensation measure?',
    options: ['The improvement would happen anyway', 'The intervention creates an outcome beyond obligations and the expected baseline', 'The project has a larger budget', 'The result needs no evidence'], correct: 1,
    explanation: 'An additional outcome would not occur without the intervention. Demonstrating it requires a credible baseline, clarity about existing legal duties and evidence that the claimed gain is not simply business as usual.',
    takeaway: 'Count only outcomes that the intervention genuinely adds.',
  },
  {
    id: 27, domain: 'mitigation', difficulty: 'Applied',
    question: 'Which approach is most appropriate when a potentially invasive species is detected on site?',
    options: ['Ignore it', 'Remove it immediately without identification or a method', 'Confirm identification, assess risk and apply a controlled response', 'Promote its spread'], correct: 2,
    explanation: 'An effective response depends on correct identification, distribution, pathway and ecological risk. Poorly planned removal can disperse propagules, damage native habitat or create repeated reinvasion.',
    takeaway: 'Control the pathway and follow-up, not just the visible individuals.',
  },
  {
    id: 28, domain: 'mitigation', difficulty: 'Applied',
    question: 'What is adaptive management?',
    options: ['Keeping a plan unchanged even when it fails', 'Adjusting actions using monitoring results and predefined triggers', 'Changing objectives without evidence', 'Acting without indicators'], correct: 1,
    explanation: 'Adaptive management treats implementation as a structured learning process. Objectives, indicators, thresholds and corrective responses are defined so that evidence can improve decisions without abandoning accountability.',
    takeaway: 'Decide in advance what result will trigger a change in the measure.',
  },
  {
    id: 29, domain: 'mitigation', difficulty: 'Applied',
    question: 'Which planting principle is strongest for habitat restoration?',
    options: ['Choose species only for rapid growth', 'Use diverse native species suited to the site and ecological objective', 'Use any ornamental mix', 'Maximise the number planted regardless of survival'], correct: 1,
    explanation: 'Species choice should reflect reference habitat, soil, climate, provenance, interactions and long-term management. A large planting count means little if the species are unsuitable or fail to establish.',
    takeaway: 'Measure establishment and ecological function, not only planting activity.',
  },
  {
    id: 30, domain: 'mitigation', difficulty: 'Advanced',
    question: 'How does life-cycle thinking improve mitigation decisions?',
    options: ['It looks only at the operating site', 'It helps avoid shifting impacts between stages, locations or materials', 'It guarantees one option has no impact', 'It replaces engineering judgement'], correct: 1,
    explanation: 'A change that reduces one local pressure may increase extraction, transport, maintenance or end-of-life impacts elsewhere. Consistent life-cycle boundaries make trade-offs visible and support better-informed design choices.',
    takeaway: 'Check whether an apparent improvement transfers the burden rather than reducing it.',
  },

  {
    id: 31, domain: 'evidence', difficulty: 'Foundation',
    question: 'Which of these is a state indicator rather than a pressure or response indicator?',
    options: ['Area of habitat cleared', 'Ecological condition of a wetland', 'Number of restoration actions delivered', 'Budget allocated'], correct: 1,
    explanation: 'State indicators describe the condition of nature. Habitat cleared is a pressure, while actions and budget are responses or inputs; a complete evidence chain links pressure, action and ecological outcome.',
    takeaway: 'Do not present an activity indicator as proof that nature has improved.',
  },
  {
    id: 32, domain: 'evidence', difficulty: 'Foundation',
    question: 'What makes an environmental indicator useful for decision-making?',
    options: ['It is easy to place in a slide', 'It is relevant, defined, measurable, comparable and linked to a decision', 'It always moves upwards', 'It has no stated unit'], correct: 1,
    explanation: 'A decision-useful indicator has a clear definition, boundary, method, frequency, owner and quality controls. It also has a target or threshold that explains how the result will influence action.',
    takeaway: 'An indicator without a decision rule may produce data but not management value.',
  },
  {
    id: 33, domain: 'evidence', difficulty: 'Applied',
    question: 'Why does the number of trees planted not prove ecological improvement on its own?',
    options: ['Trees are never relevant', 'It measures an activity, not survival, suitability or restored function', 'Trees cannot be counted', 'A larger number is always harmful'], correct: 1,
    explanation: 'Planting is an output. Ecological outcomes depend on survival, diversity, provenance, structure, connectivity, soil condition and the functions achieved over an appropriate timescale.',
    takeaway: 'Pair activity counts with condition and outcome indicators.',
  },
  {
    id: 34, domain: 'evidence', difficulty: 'Applied',
    question: 'What should accompany a credible environmental claim?',
    options: ['A natural-looking image', 'Scope, baseline, period, method, evidence and limitations', 'An absolute adjective', 'A promise without measurable criteria'], correct: 1,
    explanation: 'A credible claim allows the audience to understand what changed, compared with what, where and when. It distinguishes measured results from plans and discloses uncertainty and residual impacts.',
    takeaway: 'If the evidence cannot be checked, narrow or qualify the claim.',
  },
  {
    id: 35, domain: 'evidence', difficulty: 'Advanced',
    question: 'If ecological data are incomplete, which approach is most rigorous?',
    options: ['Hide the gap', 'Document uncertainty, use proportionate precaution and improve the evidence', 'Invent a precise figure', 'Stop all assessment permanently'], correct: 1,
    explanation: 'Incomplete data do not remove the need to decide, but uncertainty must be visible. Proportionate precaution, conservative assumptions and a targeted data-improvement plan reduce the risk of false confidence.',
    takeaway: 'Uncertainty is information to manage, not a reason to manufacture precision.',
  },
  {
    id: 36, domain: 'evidence', difficulty: 'Applied',
    question: 'Why combine Earth-observation data with field surveys?',
    options: ['Satellite data identify every species perfectly', 'Remote coverage and time series can be validated and interpreted locally', 'Fieldwork is never needed', 'The methods measure only financial value'], correct: 1,
    explanation: 'Earth observation can reveal land-cover, moisture or change patterns across large areas and time periods. Field data confirm species, condition and causal factors that imagery may not distinguish reliably.',
    takeaway: 'Use each method for what it can demonstrate and combine them where the evidence is complementary.',
  },
  {
    id: 37, domain: 'evidence', difficulty: 'Advanced',
    question: 'Which combination best supports prioritisation of a nature-related issue?',
    options: ['Visual appeal and media interest', 'Impact scale, receptor sensitivity, dependency, risk and ability to influence', 'Only the cheapest action', 'The number of available photographs'], correct: 1,
    explanation: 'Prioritisation should consider the severity and likelihood of impacts, ecological sensitivity and irreplaceability, dependencies and organisational exposure. It should also distinguish control from influence across the value chain.',
    takeaway: 'Prioritise using significance and decision leverage, not visibility alone.',
  },
  {
    id: 38, domain: 'evidence', difficulty: 'Advanced',
    question: 'What is required before making a “no net loss” claim?',
    options: ['A single restoration activity', 'Defined scope, metric, baseline, hierarchy application, equivalence, time and verified residual balance', 'A high communications budget', 'Only a count of protected hectares'], correct: 1,
    explanation: 'No-net-loss claims depend on transparent accounting of losses and gains, ecological equivalence, additionality, time lags, leakage and durability. They also require evidence that avoidance and minimisation were applied first.',
    takeaway: 'Complex balance claims need stronger evidence than simple activity statements.',
  },
  {
    id: 39, domain: 'evidence', difficulty: 'Applied',
    question: 'Why should monitoring plans include thresholds and corrective actions?',
    options: ['To make reports longer', 'To turn observations into timely management decisions', 'To guarantee no uncertainty', 'To avoid assigning responsibility'], correct: 1,
    explanation: 'A threshold identifies when performance is outside the acceptable range, while a corrective action explains what happens next. Without both, monitoring may record deterioration without changing the outcome.',
    takeaway: 'Connect each important indicator to an owner, trigger and response.',
  },
  {
    id: 40, domain: 'evidence', difficulty: 'Applied',
    question: 'Within an environmental management system, what should follow identification of a significant aspect?',
    options: ['Communication only', 'Operational controls, responsibilities, objectives where relevant and performance evaluation', 'Removal from the register', 'Assuming legal compliance is sufficient'], correct: 1,
    explanation: 'A significant aspect should be managed through appropriate controls and competence, supported by monitoring and improvement arrangements. The response should reflect compliance obligations, risk, opportunity and operational context.',
    takeaway: 'The aspects register is a decision tool, not an administrative endpoint.',
  },

  {
    id: 41, domain: 'airbus', difficulty: 'Applied',
    question: 'A stain appears beside a drain in an A400M maintenance area. What should happen first?',
    options: ['Wash it into the drain', 'Stop the source, contain the release and activate the incident procedure', 'Wait for it to evaporate', 'Cover it and continue work'], correct: 1,
    explanation: 'The immediate priority is to protect people and prevent the substance reaching soil or water. Once the source is controlled and the release contained, notification, recovery, classification and investigation can proceed.',
    takeaway: 'Control the source and pathway before focusing on clean-up or documentation.',
  },
  {
    id: 42, domain: 'airbus', difficulty: 'Applied',
    question: 'A Eurofighter-related test overlaps with a sensitive area and season for birds. What is the strongest first response?',
    options: ['Continue without review', 'Assess whether route, timing or date can avoid the interaction while preserving safety', 'Offset before assessing the impact', 'Increase the frequency of tests'], correct: 1,
    explanation: 'Operational planning may remove a spatial or temporal overlap before disturbance occurs. Safety and mission constraints remain essential, but they should be evaluated alongside receptor sensitivity and feasible alternatives.',
    takeaway: 'Use early planning to identify avoidance options before relying on behavioural or compensatory measures.',
  },
  {
    id: 43, domain: 'airbus', difficulty: 'Applied',
    question: 'When assessing an expansion of an industrial facility, which option should be examined early?',
    options: ['The option affecting the most sensitive habitat', 'Reuse of already developed land and reduction of new land take', 'The most visually prominent option', 'The option requiring the greatest lighting footprint'], correct: 1,
    explanation: 'Reusing previously altered land can avoid new soil and habitat loss, although contamination, safety, logistics and future resilience still require assessment. The comparison should be evidence-based rather than automatic.',
    takeaway: 'A strong alternatives assessment examines location, footprint, design and timing before impacts are locked in.',
  },
  {
    id: 44, domain: 'airbus', difficulty: 'Advanced',
    question: 'How can wildlife management at an aerodrome be reconciled with aviation safety?',
    options: ['Attract wildlife close to movement areas', 'Use a joint risk assessment of species behaviour, habitat and operational hazards', 'Ignore seasonal movements', 'Remove all vegetation regardless of consequences'], correct: 1,
    explanation: 'Aviation safety is the priority, but indiscriminate measures can create new attractants or transfer risk. Management should use species-specific evidence, habitat design, monitoring and coordination with operational teams.',
    takeaway: 'Manage the ecological drivers of hazardous presence, not only the animals observed at one moment.',
  },
  {
    id: 45, domain: 'airbus', difficulty: 'Applied',
    question: 'For wooden transport packaging, which evidence most improves nature-related due diligence?',
    options: ['A green colour', 'Traceable origin and independently verified responsible forest management', 'A verbal assurance', 'The lowest price without origin data'], correct: 1,
    explanation: 'Traceability links the product to its material origin and enables screening of deforestation, legality and management risks. Verification supports confidence but still needs appropriate scope and chain-of-custody controls.',
    takeaway: 'Request evidence that follows the material through the supply chain, not a generic supplier promise.',
  },
  {
    id: 46, domain: 'airbus', difficulty: 'Applied',
    question: 'What can improve mowing management on an industrial site?',
    options: ['Mow every area at the same frequency all year', 'Zone the site and align timing with safety, fire risk and ecological cycles', 'Remove monitoring', 'Introduce fast-spreading non-native plants'], correct: 1,
    explanation: 'Different areas perform different safety and ecological functions. A zoned plan can maintain access and visibility while reducing disturbance and allowing suitable vegetation structure where operational risk permits.',
    takeaway: 'Set management intensity according to function and risk rather than applying one uniform regime.',
  },
  {
    id: 47, domain: 'airbus', difficulty: 'Applied',
    question: 'What value can Earth observation add to environmental management?',
    options: ['It always replaces field verification', 'It helps detect change, compare time periods and prioritise investigation', 'It removes the need for context', 'It provides decorative images only'], correct: 1,
    explanation: 'Satellite and aerial data can reveal patterns of land cover, vegetation condition, moisture and change at useful scales. Interpretation should be validated with local evidence and a clear understanding of resolution and uncertainty.',
    takeaway: 'Use remote data to target questions and fieldwork, not to overclaim what an image proves.',
  },
  {
    id: 48, domain: 'airbus', difficulty: 'Advanced',
    question: 'An engineering change introduces a new critical mineral. What is the strongest sustainability response?',
    options: ['Approve it based on technical performance alone', 'Assess performance, traceability, sourcing risk, alternatives and life-cycle trade-offs', 'Reject every new material automatically', 'Rely only on the first-tier supplier name'], correct: 1,
    explanation: 'Engineering performance and airworthiness remain essential, while due diligence examines origin, processing, ecological and social risk, supply resilience and end-of-life implications. Alternatives should be compared using consistent requirements.',
    takeaway: 'Integrate sourcing evidence into design decisions early, when material and architecture choices are still open.',
  },
  {
    id: 49, domain: 'airbus', difficulty: 'Advanced',
    question: 'Which question best supports circularity when an aircraft component is removed during retrofit?',
    options: ['Can it be discarded immediately?', 'Can it be inspected, recertified, reused, remanufactured or recovered safely?', 'Can traceability be removed?', 'Can condition data be ignored?'], correct: 1,
    explanation: 'A circular decision considers condition, safety, certification, traceability, remaining life and demand before selecting a route. Reuse is not automatically preferable if it compromises performance or transfers greater impacts elsewhere.',
    takeaway: 'Preserve information and material value while respecting airworthiness and safety constraints.',
  },
  {
    id: 50, domain: 'airbus', difficulty: 'Advanced',
    question: 'What closes the management cycle after an environmental incident?',
    options: ['Clean-up alone', 'Cause analysis, corrective action, effectiveness review and shared learning', 'A communications message only', 'Closing the record immediately'], correct: 1,
    explanation: 'Containment and recovery address the immediate event. Root-cause analysis, corrective action and an effectiveness check reduce recurrence, while proportionate learning helps other relevant teams control the same pathway.',
    takeaway: 'A closed action is not the same as a demonstrated effective action.',
  },
];

window.KNOWLEDGE_CHECK = { DOMAINS, QUESTIONS };
